Module3 task1
htmlacademy-adaptive/1473713-mishka-23 pull request #4
Opened 2021-08-08 16:58 UTC by poisonousgirl

2021-08-09 16:18 UTC, Zakamsky requested changes
Вижу что ты очень постаралась, работа выполнена внимательно, с пониманием. Есть небольшие проблемы, но уверен ты быстро все поправишь.
Давай все отполируем перед новой темой.

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-form.less
> +.field-extra::placeholder {
в файле `page-form.less` могут находиться только элементы блока `.page-form` все остальное надо либо переименовать в `.page-form__some-name` либо вынести в другой файл.

Если в проекте есть в разных блока одинаковые плэйсхолдеры, то есть два варианта:
1. каждый инпут миксуется со своим собственным блоком, а в файле этого блока можно описать плэйсхолдеры для разных типов инпутов
2. создаем миксин в файле миксинов и добавляем его в стили каждого элемента где нужны такие стили.

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-form.less
> +.field-extra::placeholder {
обрати внимание на комментарии в этом файле - тут важно убрать лишнее из файла, делать или нет миксин - думай сама.

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-form.less
> +}
опять же, это какие то отдельные блоки, а значит они не должны быть описаны в файле `page-form.less`

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-header.less
> +}
попробуй использовать модификаторы

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-modal.less
> +.page-modal_radio-item {
опечаточка, нужно использовать двойное подчеркивание всегда. если мы отделяем им элемент.

2021-08-09 16:18 UTC, Zakamsky commented on source/less/blocks/page-footer.less
> +  background-image: url("../../img/htmlacademy.svg.svg");
тут и далее нас ждет засада от редактора который очень старался помочь. (не считая опечатки с двойным расширением)
тут нам редактор подсказал путь от файла `source/less/blocks/page-footer.less` до файла `source/img/htmlacademy.svg`
но вот в чем дело - этот путь попадет в сборку без изменений и браузер прочитает его в файле `css/style.css` после чего поверив нам на слово выйдет из папки css в корень проекта, оттуда выйдет еще на уровень и будет там искать папку картинок. на локальном сервере его видимость закончится папкой проекта он "ударится об стену" и молча останется в корне, но на сервере он пойдет бродить по другим папкам...
![image](https://user-images.githubusercontent.com/35491086/128739149-13bb36f5-e42e-426b-87d0-43fc6f133ff3.png)

(публикуй пожалуйста проект и смотри что его картинка совпадает с тем что ты видишь локально)

2021-08-10 14:06 UTC, poisonousgirl commented on source/less/blocks/about.less
> +}
нет, почему-то остается отступ. подобрала в браузере - получился отрицательный

2021-08-11 19:44 UTC, Zakamsky approved these changes
Вот теперь все отлично!

2021-08-11 19:44 UTC, merged